### PR TITLE
Dependency upgrades: Elasticsearch 7.13.0, Lucene 8.8.2, Elastic4s 7.12.2

### PR DESCRIPTION
**Pull request by alexklibisz**
plugin: upgraded to Elasticsearch 7.13.0, Lucene 8.8.2
client-elastic4s: upgraded to Elastic4s 7.12.2
other: updated to Gradle 7.0.1

### CODE REVIEW

**Comment by gurbaj5124871** [comment]
+1

**Comment by alexklibisz** [comment]
There's some subtle issue that's causing all of the tests to timeout. So far haven't had an opportunity to dig into it. Anyone else is welcome to try as well.

**Comment by gurbaj5124871** [comment]
@alexklibisz thanks man for resolving it so quickly 🙌

**Comment by gurbaj5124871** [comment]
@alexklibisz thanks man for resolving it so quickly 🙌

**Pull request merged**
