### PR TITLE
Dependencies: Upgrade Elasticsearch to 8.9.0

### PR DESCRIPTION
**Pull request by fabriziofortino**

### CODE REVIEW

**Comment by alexklibisz** [comment]
Looks like Elasticsearch had some internal changes that still compile but cause an NPE. The full internal stack trace shows up  in the Cluster Logs step: https://github.com/alexklibisz/elastiknn/actions/runs/6763768951/job/18381283342?pr=568#step:11:268

image

**Comment by fabriziofortino** [comment]
Unfortunately, I am not able to run the integration tests locally to understand the query we are trying to send to ES. It's weird though the NPE comes from `sub_searches` that have been introduced in 8.9.0 in technical preview.

**Comment by alexklibisz** [comment]
Is there anything in particular that's broken with the IT setup? It should be `task dockerRunTestingCluster` and `task jvmIntegrationTest`

**Comment by alexklibisz** [comment]
I'm looking into the error now. I looks like we're somehow throwing an exception on this line: https://github.com/elastic/elasticsearch/blob/v8.9.0/server/src/main/java/org/elasticsearch/search/builder/SubSearchSourceBuilder.java#L74C32-L74C44. I ran it with IntelliJ debugging (documented in developer-guide.md), and we're somehow getting to a state where we throw the exception defined on this line: https://github.com/alexklibisz/elastiknn/blob/main/elastiknn-plugin/src/main/scala/com/klibisz/elastiknn/query/RewriteQueryBuilder.scala#L17

image

**Comment by alexklibisz** [comment]
Nevermind. That exception in the screenshot is actually just from trying to call `toString` on the query builder. It's not actually null.

**Comment by alexklibisz** [comment]
After a bit more looking/debugging, I still don't really understand what's going on, but I think it can be narrowed down to some new interaction between:

1. The way that we asynchronously rewrite a query for an "Indexed Vector" query, in this method: https://github.com/alexklibisz/elastiknn/blob/main/elastiknn-plugin/src/main/scala/com/klibisz/elastiknn/query/ElasticsearchQueryBuilder.scala#L73-L124
2. The way the SubSearchSourceBuilder or something adjacent to it is invoking the rewrite.

I tried a few times, and I was never able to make it into the onResponse callback in here: https://github.com/alexklibisz/elastiknn/blob/main/elastiknn-plugin/src/main/scala/com/klibisz/elastiknn/query/ElasticsearchQueryBuilder.scala#L95-L112

**Comment by alexklibisz** [comment]
I got this fixed in https://github.com/alexklibisz/elastiknn/pull/574. Closing this one. @fabriziofortino , once #574 is merged, feel free to continue onto 8.9.1

**Comment by fabriziofortino** [comment]
@alexklibisz Thanks for looking into this!

I was able to solve the issues with the integration tests on my local environment. For reference, `task dockerRunTestingCluster` does not work on Mac Sonoma 14.0 + Docker Desktop 25.0.

To solve the issue:
* Enable `Use Rosetta for x86/amd64 emulation on Apple Silicon` in Settings -> General
* Disable `Access experimental features` in Settings -> Features in development -> Experimental Features
* Run the following commands (see https://github.com/docker/for-mac/issues/4822)
```
docker run -it --privileged --pid=host debian nsenter -t 1 -m -u -n -i sh

/ # sysctl -w vm.max_map_count=262144
vm.max_map_count = 262144
```
* Execute `task dockerRunTestingCluster`

**Pull request closed without merging**
