### PR TITLE
Support ES 7.17.7

### PR DESCRIPTION
**Pull request by nfsantos**
## Related issue
- #391

## Changes

Support for Elasticsearch 7.17.7.

### CODE REVIEW

**Comment by alexklibisz** [comment]
@nfsantos Can you also add this branch name here: https://github.com/alexklibisz/elastiknn/blob/main/.github/workflows/ci.yml#L6

Then it should actually run the CI.

**Comment by nfsantos** [comment]
> @nfsantos Can you also add this branch name here: https://github.com/alexklibisz/elastiknn/blob/main/.github/workflows/ci.yml#L6
> 
> Then it should actually run the CI.

I added the branch `cross-build-7.17.6` to the pull request triggers. Could you confirm that this is triggering the build? I see an workflow waiting for approval, so it seems to have worked.

**Comment by alexklibisz** [comment]
Hmm, not sure why it was skipped. Thinking...

image

**Comment by nfsantos** [comment]
> I see now. You also need to remove this line: https://github.com/alexklibisz/elastiknn/blob/cross-build-7.17.6/.github/workflows/ci.yml#L108

Done

**Comment by alexklibisz** [comment]
Hmm, pypi publish is failing. Maybe move the "publish plugin from ..." steps above the pypi step to unblock.

**Comment by alexklibisz** [comment]
It turns out I can edit your branch, so I I'm trying the thing I just suggested.

**Comment by alexklibisz** [comment]
This is failing in some interesting ways. Sorry. If you're in a big rush, I think you could also just run the assembly commands locally, produce a zip file, and maintain it internally. I'll try to figure out what it's complaining about later today.

**Comment by alexklibisz** [comment]
For now I just ran the release manually and created https://github.com/alexklibisz/elastiknn/releases/tag/7.17.7.0

**Comment by nfsantos** [comment]
That manual release does the trick for us.

Just a small question. The 7.17.7.0 binary is marked as pre-release. Does this mean that in the future you plan on changing the binary of this release? Asking this because we store a checksum of the binary, to make sure we are downloading the right thing, so if the binary changes in the future, it will break our build.

**Comment by alexklibisz** [comment]
I went ahead and marked it as a pre-release. It won't change.

I'll think more about how to support 7.x and 8.x going forward.

**Comment by nfsantos** [comment]
Ok, that will do fine for the time being. Hopefully, it will be some time until there is a 7.17.8 release.

**Comment by nevilladani-alation** [comment]
Hi @alexklibisz and @nfsantos, 
Hope you are doing well. 
We are currently using Elasticsearch 7.17.8 (because we are using Elastic Cloud service and it doesn't provide version <7.17.8 ).
I was wondering if there are any updates or plans for releasing elastiknn-7.17.8 ?

**Pull request closed without merging**
